// <auto-generated />
using System;
using System.Collections.Generic;
using LicitaEdital.Data.Offerings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicitaEdital.Data.Offerings.Migrations
{
    [DbContext(typeof(OfferingsDbContext))]
    partial class OfferingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("offerings")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicitaEdital.Domain.Offerings.OfferingAggregate.Offering", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long?>("MaxValueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("max_value_cents");

                    b.Property<long?>("MinValueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("min_value_cents");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SupplyType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("supply_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_catalogCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("catalog_codes");

                    b.PrimitiveCollection<List<string>>("_negativeKeywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("negative_keywords");

                    b.PrimitiveCollection<List<string>>("_positiveKeywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("positive_keywords");

                    b.Property<string[]>("_servedRegions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("served_regions");

                    b.PrimitiveCollection<List<string>>("_synonyms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("synonyms");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_offerings");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_offerings_organization");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_offerings_organization_name")
                        .HasFilter("is_active");

                    b.ToTable("offerings", "offerings");
                });
#pragma warning restore 612, 618
        }
    }
}
