// <auto-generated />
using System;
using System.Collections.Generic;
using LicitaEdital.Infrastructure.Data.Engagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicitaEdital.Infrastructure.Data.Engagement.Migrations
{
    [DbContext(typeof(EngagementDbContext))]
    partial class EngagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engagement")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicitaEdital.Core.Engagement.AlertPreferencesAggregate.AlertPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FilterValueRange")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("filter_value_range");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_filterModalities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("filter_modalities");

                    b.Property<string[]>("_filterStates")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("filter_states");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_alert_preferences");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_alert_preferences_organization")
                        .HasFilter("is_active");

                    b.ToTable("alert_preferences", "engagement");
                });

            modelBuilder.Entity("LicitaEdital.Core.Engagement.SavedOpportunityAggregate.SavedOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("SavedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("saved_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_saved_opportunities");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .HasDatabaseName("ix_saved_opportunities_organization_created_at");

                    b.HasIndex("OrganizationId", "OpportunityId")
                        .IsUnique()
                        .HasDatabaseName("ux_saved_opportunities_organization_opportunity");

                    b.ToTable("saved_opportunities", "engagement");
                });

            modelBuilder.Entity("LicitaEdital.Core.Engagement.SubscriptionAggregate.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_organization")
                        .HasFilter("is_active");

                    b.ToTable("subscriptions", "engagement");
                });

            modelBuilder.Entity("LicitaEdital.Core.Engagement.AlertPreferencesAggregate.AlertPreferences", b =>
                {
                    b.OwnsOne("LicitaEdital.Core.Engagement.AlertPreferencesAggregate.AlertTypes", "Types", b1 =>
                        {
                            b1.Property<Guid>("AlertPreferencesId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("ApproachingDeadline")
                                .HasColumnType("boolean")
                                .HasColumnName("alert_approaching_deadline");

                            b1.Property<bool>("DailySummary")
                                .HasColumnType("boolean")
                                .HasColumnName("alert_daily_summary");

                            b1.Property<bool>("NewCompatibleOpportunity")
                                .HasColumnType("boolean")
                                .HasColumnName("alert_new_compatible_opportunity");

                            b1.HasKey("AlertPreferencesId")
                                .HasName("pk_alert_preferences");

                            b1.ToTable("alert_preferences", "engagement");

                            b1.WithOwner()
                                .HasForeignKey("AlertPreferencesId")
                                .HasConstraintName("fk_alert_preferences_alert_preferences_id");
                        });

                    b.Navigation("Types")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
