// <auto-generated />
using System;
using System.Collections.Generic;
using LicitaEdital.Data.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LicitaEdital.Data.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.CompatibilityAggregate.OpportunityCompatibility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("engine_version");

                    b.Property<Guid?>("OfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("offering_id");

                    b.Property<string>("OfferingName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("offering_name");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<List<string>>("_attentionPoints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("attention_points");

                    b.PrimitiveCollection<List<string>>("_matchedTerms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("matched_terms");

                    b.PrimitiveCollection<List<string>>("_positiveReasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("positive_reasons");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_compatibilities");

                    b.HasIndex("EngineVersion")
                        .HasDatabaseName("ix_opportunity_compatibilities_engine_version");

                    b.HasIndex("OrganizationId", "OpportunityId")
                        .IsUnique()
                        .HasDatabaseName("ux_opportunity_compatibilities_organization_opportunity");

                    b.HasIndex("OrganizationId", "Score")
                        .HasDatabaseName("ix_opportunity_compatibilities_organization_score");

                    b.ToTable("opportunity_compatibilities", "catalog");
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("buyer_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("CityIbgeCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("city_ibge_code");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contract_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<long?>("EstimatedValueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_value_cents");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("object");

                    b.Property<string>("OfficialUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("official_url");

                    b.Property<DateTimeOffset?>("ProposalDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposal_deadline");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_opportunities");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_opportunities_published_at");

                    b.HasIndex("Source", "ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ux_opportunities_source_external_reference")
                        .HasFilter("is_active");

                    b.HasIndex("State", "Status", "ProposalDeadline")
                        .HasDatabaseName("ix_opportunities_state_status_deadline");

                    b.ToTable("opportunities", "catalog");
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.OpportunityDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_documents");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_opportunity_documents_opportunity");

                    b.ToTable("opportunity_documents", "catalog");
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.OpportunityLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("catalog_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<long?>("TotalValueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_value_cents");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit");

                    b.Property<long?>("UnitValueCents")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_value_cents");

                    b.HasKey("Id")
                        .HasName("pk_opportunity_line_items");

                    b.HasIndex("OpportunityId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_opportunity_line_items_opportunity_number");

                    b.ToTable("opportunity_line_items", "catalog");
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.Opportunity", b =>
                {
                    b.OwnsOne("LicitaEdital.Domain.Catalog.OpportunityAggregate.Modality", "Modality", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("modality_code");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("modality_label");

                            b1.HasKey("OpportunityId")
                                .HasName("pk_opportunities");

                            b1.ToTable("opportunities", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId")
                                .HasConstraintName("fk_opportunities_opportunities_id");
                        });

                    b.Navigation("Modality")
                        .IsRequired();
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.OpportunityDocument", b =>
                {
                    b.HasOne("LicitaEdital.Domain.Catalog.OpportunityAggregate.Opportunity", null)
                        .WithMany("_documents")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_opportunity_documents_opportunities_opportunity_id");
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.OpportunityLineItem", b =>
                {
                    b.HasOne("LicitaEdital.Domain.Catalog.OpportunityAggregate.Opportunity", null)
                        .WithMany("_items")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_opportunity_line_items_opportunities_opportunity_id");
                });

            modelBuilder.Entity("LicitaEdital.Domain.Catalog.OpportunityAggregate.Opportunity", b =>
                {
                    b.Navigation("_documents");

                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
