<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.Result" />
    <PackageReference Include="LicitaEdital.BuildingBlocks.Application" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LicitaEdital.Core\LicitaEdital.Core.csproj" />
  </ItemGroup>

</Project>
