<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="LicitaEdital.BuildingBlocks.Persistence" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <!-- Le pelo mapeamento de Data; Domain vem junto, transitivo. -->
    <ProjectReference Include="..\LicitaEdital.Data\LicitaEdital.Data.csproj" />
  </ItemGroup>

</Project>
