global using Ardalis.GuardClauses;
global using Ardalis.Result;
global using Ardalis.SmartEnum;
global using Ardalis.Specification;
global using LicitaEdital.BuildingBlocks.Domain.Entities;
global using LicitaEdital.BuildingBlocks.Domain.Events;
global using LicitaEdital.BuildingBlocks.Domain.Repositories;
global using Mediator;
global using Microsoft.Extensions.Logging;
